apiVersion: v1
kind: Service
metadata:
  name: attestation-service
  namespace: kubevirt
  labels:
    app: attestation-service
spec:
  selector:
    app: attestation-service
  ports:
    - port: 50051
      targetPort: 50051
      protocol: TCP
      name: grpc
  type: ClusterIP
